CREATE TABLE analises_faciais (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cliente_id UUID NOT NULL,
  pedido_id UUID NOT NULL,
  
  -- Formato geral do rosto
  formato_rosto_classificacao TEXT,
  formato_rosto_justificativa TEXT,
  formato_rosto_temperamento TEXT,
  formato_rosto_interpretacao TEXT,
  
  -- Terço superior
  testa_classificacao TEXT,
  testa_justificativa TEXT,
  testa_temperamento TEXT,
  testa_interpretacao TEXT,
  sobrancelhas_classificacao TEXT,
  sobrancelhas_justificativa TEXT,
  sobrancelhas_temperamento TEXT,
  sobrancelhas_interpretacao TEXT,
  cabelo_classificacao TEXT,
  cabelo_justificativa TEXT,
  cabelo_temperamento TEXT,
  cabelo_interpretacao TEXT,
  
  -- Terço médio
  olhos_classificacao TEXT,
  olhos_justificativa TEXT,
  olhos_temperamento TEXT,
  olhos_interpretacao TEXT,
  cilios_classificacao TEXT,
  cilios_justificativa TEXT,
  cilios_temperamento TEXT,
  cilios_interpretacao TEXT,
  palpebras_classificacao TEXT,
  palpebras_justificativa TEXT,
  palpebras_temperamento TEXT,
  palpebras_interpretacao TEXT,
  nariz_classificacao TEXT,
  nariz_justificativa TEXT,
  nariz_temperamento TEXT,
  nariz_interpretacao TEXT,
  macas_classificacao TEXT,
  macas_justificativa TEXT,
  macas_temperamento TEXT,
  macas_interpretacao TEXT,
  orelhas_classificacao TEXT,
  orelhas_justificativa TEXT,
  orelhas_temperamento TEXT,
  orelhas_interpretacao TEXT,
  
  -- Terço inferior
  boca_classificacao TEXT,
  boca_justificativa TEXT,
  boca_temperamento TEXT,
  boca_interpretacao TEXT,
  sorriso_classificacao TEXT,
  sorriso_justificativa TEXT,
  sorriso_temperamento TEXT,
  sorriso_interpretacao TEXT,
  incisivo_central_dir_classificacao TEXT,
  incisivo_central_dir_justificativa TEXT,
  incisivo_central_dir_temperamento TEXT,
  incisivo_central_dir_interpretacao TEXT,
  incisivo_lateral_dir_classificacao TEXT,
  incisivo_lateral_dir_justificativa TEXT,
  incisivo_lateral_dir_temperamento TEXT,
  incisivo_lateral_dir_interpretacao TEXT,
  canino_dir_classificacao TEXT,
  canino_dir_justificativa TEXT,
  canino_dir_temperamento TEXT,
  canino_dir_interpretacao TEXT,
  incisivo_central_esq_classificacao TEXT,
  incisivo_central_esq_justificativa TEXT,
  incisivo_central_esq_temperamento TEXT,
  incisivo_central_esq_interpretacao TEXT,
  incisivo_lateral_esq_classificacao TEXT,
  incisivo_lateral_esq_justificativa TEXT,
  incisivo_lateral_esq_temperamento TEXT,
  incisivo_lateral_esq_interpretacao TEXT,
  canino_esq_classificacao TEXT,
  canino_esq_justificativa TEXT,
  canino_esq_temperamento TEXT,
  canino_esq_interpretacao TEXT,
  queixo_classificacao TEXT,
  queixo_justificativa TEXT,
  queixo_temperamento TEXT,
  queixo_interpretacao TEXT,
  
  -- Resumo
  temperamento_predominante TEXT,
  descricao_geral TEXT,
  
  -- Metadados
  criado_em TIMESTAMP DEFAULT NOW(),
  atualizado_em TIMESTAMP DEFAULT NOW(),
  
  FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE,
  FOREIGN KEY (pedido_id) REFERENCES pedidos(id) ON DELETE CASCADE
);
